tap "homebrew/services"
tap "colindean/fonts-nonfree"

brew "ag"
brew "bash"
brew "bash-completion"
brew "coreutils"
brew "git"
brew "gpg"
brew "hub"
brew "rlwrap"
brew "wget"

cask "1password"
cask "amethyst"
cask "docker"
cask "dropbox"
cask "font-microsoft-office"
cask "fing"
cask "flux"
cask "google-chrome"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "zulip"
